name: browser
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  cached_network_image: ^3.4.1
  fluent_window: ^0.1.10
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  go_router: ^16.3.0
  google_fonts: ^6.3.2
  webview_all: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
